### PR TITLE
:memo: Add ticket link for Meetup @ Refinitiv

### PR DESCRIPTION
**Pull request by iakgoog**
Add meetup @ refinitiv event "Our Big Data and Cloud Technology Stories" on 10/10/2019 from 18:30 @ Refinitiv Thailand, U Chu Liang building 31 floor

### CODE REVIEW

**Comment by dtinth** [comment]
Thanks for the contribution!

Sorry, this repo is deprecated in favor of https://th.techcal.dev

**Comment by unnawut** [comment]
@dtinth Could you archive this repo if that's the case?

**Comment by dtinth** [comment]
@unnawut I plan to do it tonight. What has to be done:

1. Update the webpage pointing to th.techcal.dev. Note that old events should still be available as usual.
2. Remove the yearly calendar from the homepage.
3. Close all the remaining issues and pull requests with "This project is being deprecated."
4. Archive the project.

You can help with some of these if you want na krubb :smile:

**Comment by unnawut** [comment]
Sure. I can do 1 and 2. For 3, I don't know the project enough and 4, I don't have the permission to do so.

Will do 1 and 2 tonight.

**Comment by dtinth** [comment]
For 3, the algorithm is: for each issue and pull request, write a comment that the issue is closed as project is being deprecated (e.g. https://github.com/ThaiProgrammer/tech-events-calendar/pull/205#issuecomment-536861634) and click "Close and comment". I will do 3 and 4 then. Many thanks!

**Comment by unnawut** [comment]
Let's close this PR anyway. The discussion is not related to the PR now.

**Pull request closed without merging**
