### PR TITLE
Run `standard` on CI

### LINKED ISSUE #57: [Project] Run `standard` on CI
Right now I only run [standard](https://standardjs.com/) locally. Would be great to run `standard` on CI as well.

**Tasks:**

1. Add `standard` to the `"devDependencies"` in `package.json`.

2. Add a `"script"` in `package.json` to run `standard`. e.g. `yarn lint` should run `standard` on the codebase (including the `website` folder)

3. Configure CircleCI (`.circleci/circle.yml`) to run `yarn lint` on every commit.

### PR DESCRIPTION
**Pull request by suksit**
I've completed the tasks as instructed.

Close #57

### CODE REVIEW

**Comment by suksit** [comment]
Hmm... when I run `standard` as a command, the process exited successfully. However, if I run it using `yarn lint` it will exit with status 1.

I read the error messages but had no idea what was going on :\

**Comment by suksit** [comment]
So I did some research and I think we have several choices here:

1. Disable some eslint rules to make `standard` happy
2. Force `yarn lint` script to only shows the warning messages but always exit with status code 0 e.g. `"lint": "standard || exit 0"`
3. Update the source code to respect the rules

What do you think?

**Comment by dtinth** [comment]
Hey, thanks for the suggestions!

I would opt for 3. in order to ensure that future code will be consistent with standard’s guidelines. It was my own fault that I did not run the code against `standard` when I developed it (because I usually have it set up in all my projects, for some reason, I forgot to set it up here).

Since I wrote the code, I will fix it to abide by standard rules and merge it. Thanks!

**Comment by dtinth** [comment]
I fixed the ESLint warnings, but now the website is broken, I am looking into it.

**Pull request merged**
