### PR TITLE
Update calendar to 2019

### PR DESCRIPTION
**Pull request by rayriffy**
#194

### CODE REVIEW

**Comment by dtinth** [comment]
I’m also adding you as a collaborator so that you can help reviewing PRs and merging changes if/when you want to help. You can find your invite here:

https://github.com/ThaiProgrammer/tech-events-calendar/invitations

**Comment by wiput1999** [comment]
@dtinth I can also help too~

**Comment by dtinth** [comment]
@wiput1999 okay, I’ve invited you. You can find your invite here:

https://github.com/ThaiProgrammer/tech-events-calendar/invitations

**Comment by dtinth** [comment]
Thanks!

**Pull request merged**
