### PR TITLE
added TWTH Talks Tech event - Transforming with DevOps

### PR DESCRIPTION
**Pull request by nichanank**
added upcoming TW event to the data/ folder as .md and .png
https://www.eventpop.me/e/3183-twth-talks-tech-3-devops-transformation

### CODE REVIEW

**Comment by dtinth** [comment]
Thanks for the info, but the image is too big. Can you make it max. 200kb? You can convert it to jpg, if it helps.

To avoid putting the 1MB image into the source tree, can you `git reset origin/master` and create a new commit?

**Comment by nichanank** [comment]
@dtinth done! lmk if the new image works

**Comment by dtinth** [comment]
Thanks, but the image is now too small. For sharing on Facebook, the minimum image size should be 600x315.

The image is large because the PNG file is lossless and the banner contains image of a photo, which compresses badly as a PNG.

Simply converting the image into JPEG (without scaling down the image) can reduce its size to < 200kb.

Example:
thoughtworks-talks-tech-transformation-with-devops

Since dimension is large, the artifact caused by JPEG is very small.

**Comment by dtinth** [comment]
By the way, you can download the above image and put it into your PR 😄. Also, please squash your commit so that the 1MB file is not added to the Git history. Let me know if you need any help 😃.

**Comment by dtinth** [comment]
Nice, thanks!!

**Pull request merged**
